name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0
  CARGO_NET_GIT_FETCH_WITH_CLI: true
  CARGO_NET_RETRY: 10
  RUSTFLAGS: -D warnings
  RUSTUP_MAX_RETRIES: 10
  CARGO_TERM_COLOR: always
  DOCKER_REPO: "codespace-substrate-node-template"

defaults:
  run:
    shell: bash

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Install Rust
        run: |
          rustup update stable --no-self-update
          rustup target add wasm32-unknown-unknown

      - name: Install linux dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y protobuf-compiler

      - name: Build
        run: |
          cargo build --release
          mv target/release/node-template /usr/local/bin/node-template

      - name: Log in to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKER_REPO }}:${{ github.ref_name }}
            ${{ env.DOCKER_REPO }}:latest
